const BASE_FEE_APPLICABLE ={
    fee: 22000
};

const BASE_OVERTIME_FEE_APPLICABLE ={
    fee: 30000
};

const VALUE_BASE_ODER = {
    valueBase: 40000
}

const SERVICE_FEE ={
    value: 2000
}

const BASE_DISTANCE ={
    value: 3
}

const SMALL_ODER_FEE ={
    value: 3000
}

const MAX_DISTANCE_SUPPORT ={
    value: 20
}

module.exports={
    BASE_FEE_APPLICABLE: BASE_FEE_APPLICABLE,
    VALUE_BASE_ODER: VALUE_BASE_ODER,
    SERVICE_FEE:SERVICE_FEE,
    BASE_DISTANCE: BASE_DISTANCE,
    SMALL_ODER_FEE: SMALL_ODER_FEE,
    MAX_DISTANCE_SUPPORT: MAX_DISTANCE_SUPPORT,
    BASE_OVERTIME_FEE_APPLICABLE: BASE_OVERTIME_FEE_APPLICABLE
}

